baseurl = "https://sett.sh/"
title = "Sett Wai"
languageCode = "en"
theme = "kiss"
copyright = "© Sett Wai 2020"
disqusShortname = "sett-sh"
googleAnalytics = "UA-61607130-1"
Paginate = 5
enableRobotsTXT = true

[permalinks]
posts = "/posts/:year/:month/:slug"

[params]

[params.rss]
includeContent = true
authorName = "Sett Wai"
authorEmail = "exec@sett.sh"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
homeTitle = "Sett Wai"
poweredby = false
related = true
enableSocial = true
adsense = ""
codeCopy = true


[params.highlight]
style = "atom one dark"
languages = ["python", "javascript"]

[params.opengraph.twitter]
page = "settface"

[params.social]
twitter = "settface"
github = "sw00"
email = "exec@sett.sh"
rss = "posts/index.xml"

[params.social.config]
platforms = ["email", "github", "twitter", "rss"]

[params.features]
disqusOnDemand = true 

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
