baseurl = "https://sett.sh/"
title = "Sett Wai"
languageCode = "en"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/sw00\">Sett Wai</a> 2018"
disqusShortname = "sett-sh"
googleAnalytics = "UA-61607130-1"
Paginate = 5
enableRobotsTXT = true

[permalinks]
posts = "/posts/:year/:month/:slug"

[params]

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
homeTitle = "Sett Wai"
poweredby = false
related = true
enableSocial = true
adsense = ""


[params.highlight]
style = "atom one dark"
languages = ["python", "javascript"]

[params.opengraph.twitter]
page = "settface"

[params.social]
twitter = "settface"
github = "sw00"
email = "exec@sett.sh"

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
